---
- name: "Configure localhost"
  hosts: "localhost"

  vars:
    ansible_pull_service_url: "https://github.com/filipang/my-iot-podman.git"
    ansible_pull_service_sleep: "30"
    ansible_pull_timer_schedule: "*:0/30:00"
    admin_address: "192.168.0.104"
    # On gitlab 
    # ansible_path: "printer/iot-deployment/ansible"
    # On filip's personal test setup
    ansible_path: "ansible"

  tasks:

    - name: "Deploy Ansible Pull"
      ansible.builtin.import_tasks:
        file: "tasks/deploy_ansible_pull.yml"

    - name: "Deploy Podman"
      ansible.builtin.import_tasks:
        file: "tasks/deploy_podman.yml"
    
    - name: "Deploy MQTT broker"
      ansible.builtin.import_tasks:
        file: "tasks/deploy_mqtt_broker.yml"
...
