---
- name: "Start & Enable Podman Auto Update Timer"
  ansible.builtin.service:
    name: "podman-auto-update.timer"
    state: "started"
    enabled: true
  become: true

- name: "Download printer container"
  containers.podman.podman_image:
    name: "192.168.1.159:5000/printer"
    tag: "latest"
    state: "present"
    validate_certs: false
  become: true

- name: "Manage printer container Service File"
  ansible.builtin.template:
    src: "printer-container.service.j2"
    dest: "/etc/systemd/system/printer-container.service"
    owner: "root"
    group: "root"
    mode: 0644
  become: true

- name: "Manage printer container Service"
  ansible.builtin.systemd:
    name: "printer-container.service"
    state: "started"
    enabled: true
    daemon_reload: true
  become: true

- name: "Reload Services"
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
...
