---
- name: "Create the nginx container"
  containers.podman.podman_container:
    name: nginx
    hostname: nginx
    image: "docker.io/library/nginx"
    publish: 80:80
    state: started

- name: "Start & Enable Podman Auto Update Timer"
  ansible.builtin.service:
    name: "podman-auto-update.timer"
    state: "started"
    enabled: true
  become: true
...
