---
- name: "Create the nginx container"
  containers.podman.podman_container:
    name: nginx
    hostname: nginx
    image: "docker.io/library/nginx"
    state: started

- name: "Start & Enable Podman Auto Update Timer"
  ansible.builtin.service:
    name: "podman-auto-update.timer"
    state: "started"
    enabled: true
  become: true

- name: "Manage printer container Service File"
  ansible.builtin.template:
    src: "printer-container.service.j2"
    dest: "/etc/systemd/system/printer-container.service"
    owner: "root"
    group: "root"
    mode: 0644
  become: true

- name: "Manage printer container Service"
  ansible.builtin.systemd:
    name: "printer-container.service"
    state: "started"
    enabled: true
    daemon_reload: true
  become: true
...
