---
- name: "Configure Ansible Pull Service"
  ansible.builtin.template:
    src: "ansible-pull.service.j2"
    dest: "/etc/systemd/system/ansible-pull.service"
    owner: "root"
    group: "root"
    mode: 0644
  become: true

- name: "Reload Services"
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: "Enable Ansible Pull Service"
  ansible.builtin.systemd:
    name: "ansible-pull.service"
    state: "started"
    enabled: true
  become: true
...
