---
- name: "Manage container-web Service File"
  ansible.builtin.template:
    src: "container-web.service.j2"
    dest: "/etc/systemd/system/container-web.service"
    owner: "root"
    group: "root"
    mode: 0644
  become: true

- name: "Manage container-web Service"
  ansible.builtin.systemd:
    name: "container-web.service"
    state: "started"
    enabled: true
    daemon_reload: true
  become: true
...
